# Generated by Django 3.2.7 on 2021-09-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableValuem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('distance', models.IntegerField(verbose_name='distance')),
            ],
        ),
    ]
